# Generated by Django 5.0.6 on 2024-06-02 15:24

import app.server.models
import app.server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_channel_banner_channel_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='icon',
        ),
        migrations.AddField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=app.server.models.server_banner_update_path, validators=[app.server.validators.validate_image_file_extension]),
        ),
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=app.server.models.server_icon_update_path, validators=[app.server.validators.validate_icon_image_size, app.server.validators.validate_image_file_extension]),
        ),
    ]
